#NAME: Elena Escalas, Susan Krkasharian
#EMAIL: elenaescalas@g.ucla.edu, skrkasharian@yahoo.com
#ID: 704560697, 104584663

CC = gcc
RM = rm -f

default:
	@$(CC) -o lab3a lab3a.c

dist:
	@tar -cf lab3a-704560697.tar.gz README ext2_kampe.h Makefile lab3a.c

clean:
	@$(RM) lab3a *~
