#NAME: Elena Escalas
#EMAIL: elenaescalas@g.ucla.edu
#ID: 704560697

CC = gcc
RM = rm -f

default:
	@$(CC) -o lab1a lab1a.c

dist:
	@tar -cf lab1a-704560697.tar.gz README Makefile lab1a.c

clean:
	@$(RM) lab1a
